import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { normalizeEvaluationGenome } from '../src/evaluation-ai.js';

const file = process.argv[2];
if (!file) throw new Error('Usage: node ga/publish.mjs models/ga/latest.json');
const genome = normalizeEvaluationGenome(JSON.parse(fs.readFileSync(file, 'utf8')));
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const target = path.join(root, 'src', 'evolved-genome.js');
fs.writeFileSync(target, `// Generated by ga/publish.mjs. Commit this file to deploy the evolved evaluation policy.\nexport const ACTIVE_GENOME = ${JSON.stringify(genome, null, 2)};\n`);
console.log(`published ${genome.id} -> ${path.relative(root, target)}`);
