import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { normalizeEvaluationGenome } from '../src/evaluation-ai.js';

const PAIR_FORMAT = 'girls-cardgame-eval-pair-v1';

function loadPair(argv) {
  const first = argv[0];
  if (!first) throw new Error('Usage: node ga/publish.mjs PAIR.json OR node ga/publish.mjs MADOKA.json MAMI.json');
  const firstData = JSON.parse(fs.readFileSync(first, 'utf8'));
  if (firstData?.format === PAIR_FORMAT && firstData.madoka && firstData.mami) {
    return { madoka: normalizeEvaluationGenome(firstData.madoka), mami: normalizeEvaluationGenome(firstData.mami) };
  }
  const second = argv[1];
  if (!second) throw new Error('A Mami genome file is required when the first file is not a pair bundle.');
  return {
    madoka: normalizeEvaluationGenome(firstData),
    mami: normalizeEvaluationGenome(JSON.parse(fs.readFileSync(second, 'utf8'))),
  };
}

const pair = loadPair(process.argv.slice(2));
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const target = path.join(root, 'src', 'evolved-genome.js');
fs.writeFileSync(target, `// Generated by ga/publish.mjs. Commit this file to deploy the evolved character-specific evaluation policies.\nexport const ACTIVE_GENOMES = Object.freeze(${JSON.stringify(pair, null, 2)});\n`);
console.log(`published madoka=${pair.madoka.id} mami=${pair.mami.id} -> ${path.relative(root, target)}`);
